### ISSUE TITLE
Method C_Initialize returned CKR_CANT_LOCK

### ISSUE THREAD

**Issue by jariq** [jariq/Pkcs11Interop.PDF#1]
Class `Pkcs11RsaSignature` cannot be used with libraries that do not support native OS threading model for locking enabled with `CKF_OS_LOCKING_OK` flag.

**Comment by YassineKhadouch** [comment]
Thanks

**Comment by YassineKhadouch** [comment]
also if it is possible to separate the Login procedure so we can test if the PIN code is wrong and not be included in the Pkcs11RsaSignature constructor

**Comment by jariq** [comment]
Login procedure is not related to this issue.
